apiVersion: v1
kind: Service
metadata:
  name: catdog-backend
  labels:
    app: catdog-backend
    env: eks-catdog
spec:
  ports:
  - port: 80
    name: http
  selector:
    app: catdog-backend
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-backend
data:
  default.conf: |
    server {
        listen 80;

        location / {
            proxy_pass http://catdog-cat.default.svc.cluster.local;
            proxy_http_version 1.1;
        }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catdog-backend
  labels:
    app: catdog-backend
    env: eks-catdog
spec:
  replicas: 3
  selector:
    matchLabels:
      app: catdog-backend
  template:
    metadata:
      labels:
        app: catdog-backend
        env: eks-catdog
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /etc/nginx/conf.d
          readOnly: true
          name: nginx-backend
      - name: envoy
        image: 111345817488.dkr.ecr.us-east-1.amazonaws.com/aws-appmesh-envoy:v1.9.0.0-prod
        securityContext:
          runAsUser: 1337
        env:
          - name: "APPMESH_VIRTUAL_NODE_NAME"
            value: "mesh/eks-catdog/virtualNode/catdog-backend"
          - name: "ENVOY_LOG_LEVEL"
            value: "info"
          - name: "AWS_REGION"
            value: "us-east-1"
      initContainers:
        - name: proxyinit
          image: 111345817488.dkr.ecr.us-east-1.amazonaws.com/aws-appmesh-proxy-route-manager:latest
          securityContext:
            capabilities:
              add: 
                - NET_ADMIN
          env:
            - name: "APPMESH_START_ENABLED"
              value: "1"
            - name: "APPMESH_IGNORE_UID"
              value: "1337"
            - name: "APPMESH_ENVOY_INGRESS_PORT"
              value: "15000"
            - name: "APPMESH_ENVOY_EGRESS_PORT"
              value: "15001"
            - name: "APPMESH_APP_PORTS"
              value: "80"
            - name: "APPMESH_EGRESS_IGNORED_IP"
              value: "169.254.169.254"
      volumes:
        - name: nginx-backend
          configMap:
            name: nginx-backend
            items:
              - key: default.conf
                path: default.conf